[server]
host = "192.168.128.152"
port = 5247
log_level = "Warning"

[agent]
planner = "http://192.168.128.152:9090/v1/"
coordinator = "http://192.168.128.152:9090/v1/"
executor = "http://192.168.128.152:9091/v1/"

planner_name = "Assignor"
planner_instructions = "You are a review assignor for a pull request. Your answer should be brief."
planner_temperature = 0.1
planner_thinking_effort = 0 # None:0 Low:1 Medium:2 High:3
planner_thinking_output = 0 # None:0 Summary:1 Full:2
planner_timeout = 3600

executor_name = "Reviewer"
executor_instructions = "You are a reviewer for a pull request. Your review should be correct and strict."
executor_temperature = 0.1
executor_thinking_effort = 0 # None:0 Low:1 Medium:2 High:3
executor_thinking_output = 0 # None:0 Summary:1 Full:2
executor_timeout = 3600

[gitlab]
url = "http://192.168.128.147"
expand_submodule_diffs = false
pr_commands = [
    "/describe --pr_description.final_update_message=false",
    "/review",
    "/improve",
]
handle_push_trigger = false
push_commands = [
    "/describe",
    "/review",
]
# Configure SSL validation for GitLab. Can be either set to the path of a custom CA or disabled entirely.
ssl_verify = false
