[common]
default_language = "ja"
git_provider = "github"
warm_up = true

[server]
url = ""
log_level = "Warning"
trust_certificate = false # always trust certificate
trusted_certificates = [""]

[agent]

# Used for summarize diffs, simple task.
assistant = "https://api.openai.com/v1"
assistant_name = "Assistant"
assistant_model = "gpt-5-mini"
assistant_instructions = "You are an assistant for other agents. Your answer should be brief."
assistant_temperature = 0.1
assistant_thinking_effort = 0 # None:0 Low:1 Medium:2 High:3
assistant_thinking_output = 0 # None:0 Summary:1 Full:2
assistant_timeout = 1200

# Used for planning reviews, slightly complicated logical reasoning task.
planner = "https://api.openai.com/v1"
planner_name = "Assignor"
planner_model = "gpt-5-mini"
planner_instructions = "You are a review assignor for a pull request. Your answer should be brief."
planner_temperature = 0.1
planner_thinking_effort = 0 # None:0 Low:1 Medium:2 High:3
planner_thinking_output = 0 # None:0 Summary:1 Full:2
planner_timeout = 1200

# Used for each review and organizing reviews, needs long context and understanding long sentences.
executor = "https://api.openai.com/v1"
executor_name = "Reviewer"
executor_model = "gpt-5-mini"
executor_instructions = "You are a reviewer for a pull request. Your review should be correct and strict."
executor_temperature = 0.1
executor_thinking_effort = 0 # None:0 Low:1 Medium:2 High:3
executor_thinking_output = 0 # None:0 Summary:1 Full:2
executor_timeout = 1200

[github]
name = "XXX" # repository username
ssl_verify = true

[gitlab]
url = ""
ssl_verify = false

[review]
# file extensions to review
target_extensions = ["c","cpp", "cxx", "cc", "h", "hpp", "inl", "cs", "py", "rs"]
