[openai]
api_key = "XXX"

[github]
personal_access_token = "XXX" # personal access token
shared_secret = "XXX" # webhook secret

[gitlab]
personal_access_token = "XXX" # personal access token
shared_secret = "XXX"  # webhook secret

